# Generated by Django 3.0.8 on 2021-03-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='password',
            new_name='app_password',
        ),
    ]
