# Generated by Django 3.0.8 on 2021-03-15 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='architect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='architect_id', to='hassmalieapp.Worker'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_id', to='hassmalieapp.Worker'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Costumer'),
        ),
    ]
