# Generated by Django 3.0.8 on 2021-02-14 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license', models.DateField(default=None)),
                ('report_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='mybusiness',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='M', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='title',
            field=models.CharField(default='Manager', max_length=70),
        ),
    ]
