# Generated by Django 3.0.8 on 2021-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210214_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='title',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Deputy Director'), ('R', 'Regular')], default='M', max_length=1),
        ),
    ]
