# Generated by Django 3.0.8 on 2021-03-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210306_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='deputy_director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='D', to=settings.AUTH_USER_MODEL),
        ),
    ]
