# Generated by Django 3.0.8 on 2021-03-14 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210313_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='worker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Worker'),
        ),
    ]
