# Generated by Django 3.0.8 on 2021-01-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_auto_20210115_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybusiness',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='MyBusiness',
        ),
    ]
