# Generated by Django 3.0.8 on 2021-03-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_auto_20210315_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
