# Generated by Django 3.0.8 on 2021-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_auto_20210306_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybusiness',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
