# Generated by Django 3.0.8 on 2021-01-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0005_remove_useraccount_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='title',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Deputy Director'), ('R', 'Regular')], default='M', max_length=1),
        ),
        migrations.CreateModel(
            name='MyBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField(default=None)),
                ('license_validity', models.DateField(default=None)),
                ('insurance_validity', models.DateField(default=None)),
                ('insurance_up_to_age', models.IntegerField(default=None)),
                ('image', models.ImageField(upload_to='')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
    ]
