# Generated by Django 3.0.8 on 2021-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0007_auto_20210115_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='title',
            field=models.CharField(choices=[('M', 'Manager'), ('D', 'Deputy Director'), ('R', 'Regular')], default='M', max_length=1),
        ),
    ]
