# Generated by Django 3.0.8 on 2021-01-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0008_auto_20210115_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
    ]
