# Generated by Django 3.0.5 on 2021-06-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(default=None)),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('title', models.CharField(choices=[('M', 'Manager'), ('D', 'Deputy Director')], default='M', max_length=1)),
                ('photo', models.ImageField(upload_to='usersphotos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='bids/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='customers/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='MyBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('deputy_director', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='D', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='M', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_building', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('buildingImage', models.ImageField(default=None, upload_to='projects/buildingimages/')),
                ('progress', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='workers/photos/')),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('title', models.CharField(choices=[('R', 'Regular'), ('C', 'Contractor'), ('A', 'Architect')], default='R', max_length=1)),
                ('id_photo', models.ImageField(upload_to='workers/ids/')),
                ('rate_per_day', models.FloatField(default=None, null=True)),
                ('license', models.ImageField(default=None, upload_to='workers/licenses/')),
                ('permit', models.ImageField(default=None, upload_to='workers/permits/')),
                ('permit_type', models.CharField(default=None, max_length=255, null=True)),
                ('permit_validity', models.DateField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('U', 'user'), ('W', 'worker'), ('C', 'customer')], default='W', max_length=1)),
                ('author_id', models.IntegerField()),
                ('date', models.DateField(default=None)),
                ('time', models.TimeField()),
                ('description', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to='tasks/')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_item_price', models.FloatField()),
                ('photo', models.ImageField(upload_to='bids/symbols/')),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Bid')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(default=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='reports/')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('P', 'Plans'), ('I', 'Images'), ('Pay', 'Payments')], default='I', max_length=3)),
                ('file', models.FileField(upload_to='projects/projectsfiles/')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='architect_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='architect_id', to='hassmalieapp.Worker'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_id', to='hassmalieapp.Worker'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='my_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness'),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
                ('annotation', models.CharField(max_length=255)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Bid')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='my_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.IntegerField(default=None, unique=True)),
                ('license_validity', models.DateField(default=None)),
                ('insurance_validity', models.DateField(default=None)),
                ('insurance_up_to_age', models.IntegerField(default=None)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=None, upload_to='carimages/')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='my_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness'),
        ),
        migrations.AddField(
            model_name='bid',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project'),
        ),
    ]
