# Generated by Django 3.0.5 on 2021-06-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='my_business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness'),
            preserve_default=False,
        ),
    ]
