# Generated by Django 3.0.5 on 2021-05-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='photo',
            field=models.ImageField(upload_to='bids/symbols/'),
        ),
    ]
