# Generated by Django 3.0.5 on 2021-05-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='buildingImage',
            field=models.ImageField(upload_to='projects/buildingimages/'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('P', 'Plans'), ('B', 'Bids'), ('I', 'Images'), ('Pay', 'Payments')], default='I', max_length=3)),
                ('file', models.FileField(upload_to='projects/<django.db.models.fields.CharField>/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project')),
            ],
        ),
    ]
