# Generated by Django 3.0.5 on 2021-06-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symbol',
        ),
    ]
