# Generated by Django 3.0.5 on 2021-05-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210526_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
