# Generated by Django 3.0.5 on 2021-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210521_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default=None, upload_to='carimages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='buildingImage',
            field=models.ImageField(default=None, upload_to='projects/buildingimages/'),
        ),
    ]
