# Generated by Django 3.1.7 on 2021-03-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0002_auto_20210315_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(choices=[('R', 'Regular'), ('C', 'Contractor'), ('A', 'Architect')], default='R', max_length=1),
        ),
    ]
