# Generated by Django 3.0.5 on 2021-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_projectfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='company_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacture_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
