# Generated by Django 3.0.5 on 2021-06-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_projectfile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('payment_date', models.FloatField()),
                ('pay_type', models.IntegerField()),
                ('contact_mail', models.CharField(max_length=255)),
                ('payer_name', models.CharField(max_length=255)),
                ('pay_condition', models.CharField(max_length=255)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Bid')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
    ]
