# Generated by Django 3.0.5 on 2021-05-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_auto_20210527_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='license',
            field=models.ImageField(default=None, upload_to='workers/licenses/'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
