# Generated by Django 3.0.5 on 2021-06-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0003_symbol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
