# Generated by Django 3.0.5 on 2021-06-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0004_delete_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('P', 'Plans'), ('I', 'Images'), ('Pay', 'Payments')], default='I', max_length=3)),
                ('name', models.TextField(default='')),
                ('file', models.FileField(upload_to='projects/projectsfiles/')),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Project')),
            ],
        ),
    ]
