# Generated by Django 3.0.5 on 2021-06-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0004_auto_20210605_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rate_per_day',
            field=models.FloatField(default=0, null=True),
        ),
    ]
