# Generated by Django 3.0.5 on 2021-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0005_projectfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidTable',
        ),
    ]
