# Generated by Django 3.0.5 on 2021-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0005_auto_20210606_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
