# Generated by Django 3.0.5 on 2021-06-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0006_delete_bidtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_item_price', models.FloatField()),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Bid')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
    ]
