# Generated by Django 3.0.5 on 2021-06-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0005_auto_20210606_0241'),
        ('hassmalieapp', '0007_auto_20210605_2142'),
    ]

    operations = [
    ]
