# Generated by Django 3.0.5 on 2021-06-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0008_merge_20210607_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='bid_id',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='count',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='total_item_price',
        ),
        migrations.AddField(
            model_name='label',
            name='version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BidTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_item_price', models.FloatField()),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hassmalieapp.Bid')),
                ('my_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hassmalieapp.MyBusiness')),
            ],
        ),
    ]
