# Generated by Django 3.0.5 on 2021-06-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0009_auto_20210612_1432'),
        ('hassmalieapp', '0007_bid_deleted'),
    ]

    operations = [
    ]
