# Generated by Django 3.0.5 on 2021-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0010_merge_20210616_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtable',
            name='version',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='w',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.FloatField(),
        ),
    ]
