# Generated by Django 3.0.5 on 2021-06-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hassmalieapp', '0011_auto_20210616_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver_email',
            field=models.TextField(default='', null=True),
        ),
    ]
